### ISSUE TITLE
Builder path

### ISSUE THREAD

**Issue by srl295** [GuySmithFerrier/NCLDR#1]
Builder seems to want the parent directory of "core" as its input path.  So `C:\whatever`  where exists `c:\whatever\core\common\main\en.xml` for example.  

If it's the same to you, it'd be nice if it could actually take the path to and including `common`, so in my example making the input path be `c:\whatever\core\common`. Then one could, for example, point it at a copy of the data from trunk…

**Comment by GuySmithFerrier** [comment]
Good catch. I will fix that. Thanks.

**Comment by GuySmithFerrier** [comment]
Fixed in 0.0.0.004-Alpha.
