### ISSUE TITLE
NCLDR Explorer: RTL text

### ISSUE THREAD

**Issue by srl295** [GuySmithFerrier/NCLDR#2]
At least in the '.net comparison' panel, RTL text such as Arabic should have a RTL default for 'Native Display Name'. 

At leastthe .NET and NCLDR displays are consistent.

**Comment by GuySmithFerrier** [comment]
Agreed. I will fix that. Thanks.

**Comment by GuySmithFerrier** [comment]
Fixed in 0.0.0.004-Alpha.
