### ISSUE TITLE
Minor issues: Builder, Explorer

### ISSUE THREAD

**Issue by srl295** [GuySmithFerrier/NCLDR#3]
• In the Explorer: should disable the other tabs instead of crash if you try to switch out before loading data. Get an assert, 'data not loaded yet'

• In the Builder: shows a bunch of text as it loads CLDR data, should show something like "All done!" at the end to know that it's completed.

**Comment by GuySmithFerrier** [comment]
1. Oops. Yes, I will fix the bug in NCldrExplorer.
2. I'm not sure what you are saying - NCldrBuilderCmd _does_ display a "Done." message when it is complete.

**Comment by srl295** [comment]
1. I was on the GUI. I saw the Done on the video of the Cmd, but didn't see a Done when loading CLDR into the Builder. or did I just not wait long enough?

**Comment by GuySmithFerrier** [comment]
Hmm. That's odd. The GUI also displays "Done." when it is complete. It is in the "Build Progress" box. Let me know if you can reproduce an example where you don't get a "Done." message.

**Comment by mrlacey** [comment]
This caught me out too. Output, including the "Done" message, is added at the top of the list/textbox, rather than at the bottom which is the defacto convention I've seen almost everywhere else.

**Comment by GuySmithFerrier** [comment]
Ok, point taken. I'll make a change here.

**Comment by GuySmithFerrier** [comment]
Fixed in 0.0.0.004-Alpha.
