### ISSUE TITLE
Configure inclusion of CalendarPreferences in BuilderGUI

### ISSUE THREAD

**Issue by mrlacey** [GuySmithFerrier/NCLDR#4]
There is no option to specify whether CalendarPreferences is included in data files generated by BuilderGUI. This means it's always included, and therefore adds to file size, whether it's wanted or not.

**Comment by GuySmithFerrier** [comment]
Good catch. It will be added in the next release. However, for now the feature is there and works but you will need to manually change the NCLDRBuilder.config file to change the setting. Also note that the Calendar Preferences take up a total of 0.02% of the file size (3350 bytes in total).

**Comment by mrlacey** [comment]
Yeah, a minor thing  I was building a very small, targeted data file and so the proportional size was much larger

**Comment by GuySmithFerrier** [comment]
Fixed in 0.0.0.004-Alpha.
