### ISSUE TITLE
BuilderGUI doesn't remember specified cultures

### ISSUE THREAD

**Issue by mrlacey** [GuySmithFerrier/NCLDR#5]
If in the BuilderGUI the "Include only those checked below" is selected, any selected cultures aren't included when the config file is saved (and reloaded)

**Comment by GuySmithFerrier** [comment]
Got it. The data is saved correctly but not loaded correctly. It will be fixed in the next release.

**Comment by GuySmithFerrier** [comment]
Fixed in 0.0.0.004-Alpha.
