### ISSUE TITLE
NUGET Package

### ISSUE THREAD

**Issue by denis44** [GuySmithFerrier/NCLDR#9]
That's great!! CDLR database is really missing in .NET. Do you have any plans to add this project to NUGET package repository? It will be very helpful.

**Comment by GuySmithFerrier** [comment]
Hi Denis. Yes, NCLDR is already available on Nuget: https://nuget.org/packages/NCLDR/.

**Comment by vgrigoriu** [comment]
I'm curious, why doesn't the nuget package include ncldr.dat? Is it because of licensing issues, i.e. you're not allowed to redistribute it? Or would the package get too big?
